<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 基础项目信息 -->
    <groupId>com.luyang</groupId>
    <artifactId>dependencies</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>0.0.1-SNAPSH0T</revision>
        <!-- SpringBoot SpringCloud SpringCloudAlibaba 版本 https://sca.aliyun.com/docs/2023/overview/version-explain/?spm=5176.29160081.0.0.511d1d28E6mG9S -->
        <spring-boot-dependencies.version>3.4.0</spring-boot-dependencies.version>

        <mybatis-plus-bom.version>3.5.12</mybatis-plus-bom.version>
        <redisson-spring-boot-starter.version>3.45.1</redisson-spring-boot-starter.version>

        <hutool-all.version>5.8.37</hutool-all.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot 基础依赖管理 -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Spring Boot Web Starter（移除默认的 Tomcat） -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-tomcat</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>${mybatis-plus-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson-spring-boot-starter.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-core</artifactId>
                <version>${hutool-all.version}</version>
            </dependency>

            <dependency>
                <groupId>com.luyang</groupId>
                <artifactId>luyang-framework-starter-base</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.luyang</groupId>
                <artifactId>luyang-framework-starter-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.luyang</groupId>
                <artifactId>luyang-framework-starter-redisson</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.luyang</groupId>
                <artifactId>luyang-framework-starter-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.luyang</groupId>
                <artifactId>luyang-framework-starter-web</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
