<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.cn-luyang</groupId>
    <artifactId>dependencies</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>dependencies</name>
    <description>dependencies</description>
    <url>https://github.com/cn-luyang/luyang-framework</url>

    <!-- 开源协议信息 -->
    <licenses>
        <license>
            <name>Apache License Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <!-- Git 仓库信息 -->
    <scm>
        <url>https://github.com/cn-luyang/luyang-framework</url>
        <connection>scm:git:https://github.com/cn-luyang/luyang-framework.git</connection>
        <developerConnection>scm:git:https://github.com/cn-luyang/luyang-framework.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <!-- 开发者信息 -->
    <developers>
        <developer>
            <name>luyang</name>
            <email>cn_luyang@163.com</email>
        </developer>
    </developers>

    <distributionManagement>
        <!-- 快照版发布地址 -->
        <snapshotRepository>
            <id>central</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
        </snapshotRepository>
        <!-- 正式版发布地址 -->
        <repository>
            <id>central</id>
            <url>https://central.sonatype.com/repository/maven-releases/</url>
        </repository>
    </distributionManagement>

    <properties>
        <revision>2026.05.19.01</revision>
        <maven-gpg-plugin.version>3.2.7</maven-gpg-plugin.version>
        <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
        <flatten-maven-plugin.version>1.7.2</flatten-maven-plugin.version>
        <maven-javadoc-plugin.version>3.11.2</maven-javadoc-plugin.version>
        <central-publishing-maven-plugin.version>0.8.0</central-publishing-maven-plugin.version>

        <!-- SpringBoot SpringCloud SpringCloudAlibaba 版本 https://sca.aliyun.com/docs/2023/overview/version-explain/?spm=5176.29160081.0.0.511d1d28E6mG9S -->
        <spring-boot-dependencies.version>3.5.0</spring-boot-dependencies.version>
        <spring-cloud-dependencies.version>2025.0.0</spring-cloud-dependencies.version>
        <!-- Nacos官网 https://nacos.io/?spm=5238cd80.5e8a737d.0.0.3e5d7e84StoDVK -->
        <spring-cloud-alibaba-dependencies.version>2023.0.3.3</spring-cloud-alibaba-dependencies.version>

        <!-- Dubbo官网 https://cn.dubbo.apache.org/zh-cn/ -->
        <dubbo-bom.version>3.3.4</dubbo-bom.version>
        <!-- MyBatis-Plus官网 https://www.baomidou.com/ -->
        <mybatis-plus-bom.version>3.5.12</mybatis-plus-bom.version>

        <redisson-spring-boot-starter.version>3.45.1</redisson-spring-boot-starter.version>

        <commons-lang3.version>3.20.0</commons-lang3.version>
        <!-- Hutool官网 https://hutool.cn/ -->
        <hutool.version>5.8.39</hutool.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <mysql-connector-java.version>8.0.33</mysql-connector-java.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot 基础依赖管理 -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Spring Boot Web Starter（移除默认的 Tomcat） -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-tomcat</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-bom</artifactId>
                <version>${dubbo-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>${mybatis-plus-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson-spring-boot-starter.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-core</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-extra</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql-connector-java.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-mapstruct-binding</artifactId>
                <version>${lombok-mapstruct-binding.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-base-util</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-starter-base</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-starter-dict</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-starter-dubbo</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-starter-feign</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-starter-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-starter-redisson</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-starter-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cn-luyang</groupId>
                <artifactId>luyang-framework-starter-web</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>${maven-source-plugin.version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>${maven-javadoc-plugin.version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven-gpg-plugin.version}</version>
                        <executions>
                            <execution>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>flatten-maven-plugin</artifactId>
                        <version>${flatten-maven-plugin.version}</version>
                        <configuration>
                            <updatePomFile>true</updatePomFile>
                            <flattenMode>resolveCiFriendliesOnly</flattenMode>
                        </configuration>
                        <executions>
                            <execution>
                                <id>flatten</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>flatten</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>flatten.clean</id>
                                <phase>clean</phase>
                                <goals>
                                    <goal>clean</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>${central-publishing-maven-plugin.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
